Staging I
Agetuni/the_future_mobility_frontend pull request #15
Opened 2023-01-18 10:56 UTC by Agetuni

###  The future mobility 

- user can register and sign in
- can able to create and delete vehicles 
- can see detailed information on vehicles
- can reserve a car for a test ride
- can see reservation list 
- can cancel a reservation 

###  [Backend pull request ]()

![image](https://user-images.githubusercontent.com/45159038/213152376-883593eb-676d-4ce1-9042-f86ac2b9b77a.png)
![image](https://user-images.githubusercontent.com/45159038/213152469-a6b51aba-7403-4cf4-aec6-d1c2a84e83ff.png)
![image](https://user-images.githubusercontent.com/45159038/213152740-94ee1586-c66e-4ab3-8510-ba8482da372b.png)
![image](https://user-images.githubusercontent.com/45159038/213152793-e5c9be4f-8c0d-41cc-916e-f467bde8d1d2.png)
![image](https://user-images.githubusercontent.com/45159038/213152897-3cafee31-e680-4f56-ae9f-4c77b3fbde86.png)

2023-01-18 13:04 UTC, Meltrust requested changes
Hi @Agetuni,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!






### To highlight:

-  App is working well✔️ 
-  Good readme ✔️ 
-  Nice frontend ✔️ 



#### You are really close to finishing the Microverse program!! Keep it up! 👍👍👍

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

### After implementing the requested changes, please submit another review request. ♻️
_Check the comments under the review._

_I strongly recommend you take them into account as they can improve your final evaluation._





Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the previous reviews unless it is requested otherwise._**

------

2023-01-18 13:04 UTC, Meltrust commented on README.md
> +_NOTE: we recommend using the [MIT license](https://choosealicense.com/licenses/mit/) - you can set it up quickly by [using templates available on GitHub](https://docs.github.com/en/communities/setti
- [x] This is just placeholder text to help you add a license.  Kindly remove it.

2023-01-18 13:04 UTC, Meltrust commented on README.md
> +<a name="readme-top"></a>
- [ ] You included some frontend tests, however, some of them are not passing on my end:


![image](https://user-images.githubusercontent.com/57421823/213176914-0e4ab5cc-dd49-431b-af1c-210b9d5076d9.png)

Kindly check if the tests are not passing for you, and if the don't please correct them to preserve your app's integrity. 💪

2023-01-18 13:04 UTC, Meltrust commented on src/components/reservations/MyReservations.js
> +    console.log('ue effe ')
According to the [Javascript general requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/javascript_best_practices.md):

![image](https://user-images.githubusercontent.com/57421823/213177408-69ea01e3-0c54-4ed0-a4df-cf55e85d6b42.png)

Your app has many console.logs:

![image](https://user-images.githubusercontent.com/57421823/213177524-999914de-2c71-4a65-bc94-64db9d215a96.png)

Therefore:

- [x] Kindly remove these debugging console logs in order to meet this requirement.  You can safely delete them.

2023-01-18 13:04 UTC, Meltrust commented on src/redux/resevation_reducer.js
> +  debugger;
- [ ] When trying to cancel a reservation, I hit this debugger.  Kindly remove it so your app works as intended for users.

2023-01-18 13:04 UTC, Meltrust commented on src/components/assets/styles/main.scss
> +@import 'design';
In the mobile view:

- [ ] There seems to be no hamburger menu, or some sort of menu to open the navigation.  Kindly add one.
- [ ] The mobile menu is getting overflowed by the cars on the main page:

![image](https://user-images.githubusercontent.com/57421823/213178480-63c890ea-2835-490a-96ae-5081739b7882.png)


Kindly correct this bug.  That way, your mobile app will be beautiful, and professional. 👍

2023-01-19 08:42 UTC, Agetuni commented on README.md
> +_NOTE: we recommend using the [MIT license](https://choosealicense.com/licenses/mit/) - you can set it up quickly by [using templates available on GitHub](https://docs.github.com/en/communities/setti
Fixed

2023-01-19 13:06 UTC, Meltrust approved these changes
Hi @Agetuni,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!






### To highlight:

-  Reservations frontend has been fixed✔️ 
-  Good readme ✔️ 
-  Nice documentation ✔️
-  Good code organization ✔️ 
-  Debugging code has been removed ✔️ 



#### You are really close to finishing the Microverse program!! Keep it up! 👍👍👍

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

### After implementing the requested changes, please submit another review request. ♻️
_Check the comments under the review._

_I strongly recommend you take them into account as they can improve your final evaluation._





Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the previous reviews unless it is requested otherwise._**

------

2023-01-19 13:06 UTC, Meltrust commented on src/__tests__/reservations/reservation.test.js
> +});
- [ ] There are still some issues with the frontend tests:

![image](https://user-images.githubusercontent.com/57421823/213449385-32b72dbc-7bbb-4564-854a-a28c3be319da.png)

![image](https://user-images.githubusercontent.com/57421823/213449444-59cdaeee-b373-40d8-bbca-456ed5933389.png)

![image](https://user-images.githubusercontent.com/57421823/213449486-c5413256-9fa3-4c5a-a74b-71138fb80f31.png)

There is a test suite that is not running and a failed test.  

Kindly, follow the error messages and ensure that all your tests are passing.

You've come all this way, to the top of the Microverse program.  I'm pretty sure you are able to power through this small issue! 💪

2023-01-19 17:25 UTC, merged